"use strict";

export const HASH = "#";
export const HREF = "href";
export const DISPLAY = "display";
export const STATE_KEY = "state";
export const TRANSFORM = "transform";
export const SCROLL_DELAY = 10;
export const DECELERATION = 0.0333333;
export const UP_DIRECTION = +1;
export const EMPTY_STRING = "";
export const BLANK_TARGET = "_blank";
export const INDEX_PREPEND = "index";
export const DOWN_DIRECTION = -1;
export const TRANSFORM_ORIGIN = "transformOrigin";
export const CLIENT_FILE_NAME = "client.js";
export const PORTRAIT_ORIENTATION = "portrait";
export const LANDSCAPE_ORIENTATION = "landscape";
export const TOP_LEFT_TRANSFORM_ORIGIN = "top left";
export const ORIENTATION_PORTRAIT_QUERY = "(orientation: portrait)";
export const CLIENT_CSS_SELECTORS_STRING = "div.view > div.document > div";
