"use strict";

export const HASH = "#";
export const HREF = "href";
export const FLEX = "flex";
export const DISPLAY = "display";
export const TRANSFORM = "transform";
export const UP_DIRECTION = "up";
export const EMPTY_STRING = "";
export const BLANK_TARGET = "_blank";
export const MARGIN_RIGHT = "marginRight";
export const INITIAL_SCALE = 1/3;
export const MARGIN_BOTTOM = "marginBottom";
export const INDEX_PREPEND = "index";
export const LEFT_DIRECTION = "left";
export const DOWN_DIRECTION = "down";
export const DRAFT_VIEW_MODE = "draft";
export const RIGHT_DIRECTION = "right";
export const TRANSFORM_ORIGIN = "transformOrigin";
export const CLIENT_FILE_NAME = "client.js";
export const SCROLL_TOP_DELTA = 1.0;
export const SCROLL_SPEED_DELTA = 0.002;
export const PORTRAIT_ORIENTATION = "portrait";
export const LANDSCAPE_ORIENTATION = "landscape";
export const TOP_LEFT_TRANSFORM_ORIGIN = "top left";
export const ORIENTATION_PORTRAIT_QUERY = "(orientation: portrait)";
export const CLIENT_CSS_SELECTORS_STRING = "div.view > div.document > div";
