"use strict";

export const svgFill = "#fff";
export const menuDivGap = "32px";
export const borderWidth = "4px";
export const borderRadius = "8px"
export const borderColour = "#fff";
export const checkboxSize = "48px";
export const buttonsDivGap = "32px";
export const overlayDivGap = "48px";
export const menuDivPadding = "64px";
export const checkboxDivGap = "32px";
export const menuButtonSize = "64px";
export const checkboxesDivGap = "48px";
export const menuButtonPadding = "8px";
export const checkboxSpanColour = "#fff";
export const instructionsDivWidth = "640px";
export const checkboxSpanFontSize = checkboxSize; ///
export const instructionsFontSize = "24px";
export const closeOverlayButtonTop = "24px";
export const instructionsFontFamily = "sans-serif";
export const closeOverlayButtonRight = "24px";
export const menuDivBackgroundColour = "#222";
export const instructionsCheckboxSize = "32px";
export const instructionsButtonColour = "#fff";
export const checkboxBackgroundColour = "#000";
export const closeOverlayButtonColour = "#222";
export const instructionsButtonPadding = "16px";
export const overlayDivBackgroundColour = "#fff";
export const instructionsButtonFontSize = "24px";
export const instructionsCheckboxDivGap = "18px";
export const closeOverlayButtonFontSize = "24px";
export const instructionsParagraphMargin = "12px";
export const closeOverlayButtonFontFamily = "sans-serif";
export const instructionsCheckboxDivMarginTop = "36px";
export const instructionsCheckboxDivPaddingRight = "36px";
export const mobileInstructionsButtonBackgroundColour = "#080";
export const desktopInstructionsButtonBackgroundColour = "#008";
