"use strict";

export const svgFill = "#fff";
export const menuDivGap = "32px";
export const borderWidth = "3px";
export const borderRadius = "8px"
export const borderColour = "#fff";
export const checkboxSize = "24px";
export const buttonsDivGap = "32px";
export const menuDivPadding = "64px";
export const checkboxDivGap = "32px";
export const menuButtonSize = "24px";
export const containerDivGap = "24px";
export const backButtonColour = "#00f";
export const checkboxesDivGap = "48px";
export const menuButtonPadding = "8px";
export const backButtonPadding = "12px";
export const checkboxSpanColour = "#fff";
export const containerDivPadding = "24px";
export const containerDivMaxWidth = "960px";
export const containerDivFontSize = "48px";
export const checkboxSpanFontSize = checkboxSize; ///
export const containerDivFontFamily = "sans-serif";
export const instructionsDivPadding = "36px";
export const menuDivBackgroundColour = "#222";
export const hideOverlayButtonColour = "#222";
export const instructionsButtonWidth = "320px";
export const instructionsButtonColour = "#fff";
export const checkboxBackgroundColour = "#000";
export const instructionsButtonPadding = "12px";
export const overlayDivBackgroundColour = "#fff";
export const instructionsCheckboxDivGap = "12px";
export const instructionParagraphMargin = "12px";
export const mobileInstructionsButtonBackgroundColour = "#080";
export const desktopInstructionsButtonBackgroundColour = "#008";
