"use strict";

export const svgFill = "#fff";
export const menuDivGap = "32px";
export const borderWidth = "3px";
export const borderRadius = "8px"
export const borderColour = "#fff";
export const checkboxSize = "48px";
export const buttonsDivGap = "32px";
export const menuDivPadding = "64px";
export const checkboxDivGap = "32px";
export const menuButtonSize = "64px";
export const containerDivGap = "1em";
export const backButtonColour = "#00f";
export const checkboxesDivGap = "48px";
export const menuButtonPadding = "8px";
export const backButtonPadding = "0.5em";
export const checkboxSpanColour = "#fff";
export const containerDivPadding = "1em";
export const containerDivMaxWidth = "960px";
export const checkboxSpanFontSize = checkboxSize; ///
export const containerDivFontFamily = "sans-serif";
export const instructionsDivPadding = "36px";
export const menuDivBackgroundColour = "#222";
export const hideOverlayButtonColour = "#222";
export const instructionsButtonWidth = "320px";
export const instructionsButtonColour = "#fff";
export const checkboxBackgroundColour = "#000";
export const instructionsButtonPadding = "1em";
export const overlayDivBackgroundColour = "#fff";
export const instructionsCheckboxDivGap = "0.5em";
export const instructionParagraphMargin = "1em";
export const mobileInstructionsButtonBackgroundColour = "#080";
export const desktopInstructionsButtonBackgroundColour = "#008";

export const containerDivPortraitFontSize = "48px";
export const containerDivLandscapeFontSize = "24px";
export const instructionsCheckboxPortraitSize = "48px";
export const instructionsCheckboxLandscapeSize = "24px";
export const instructionsCheckboxPortraitBorderWidth = "4px";
export const instructionsCheckboxLandscapeBorderWidth = "2px";
export const instructionsCheckboxPortraitBorderRadius = "4px";
export const instructionsCheckboxLandscapeBorderRadius = "2px";
